#!/bin/bash

path_dir=(/home/aman/)

if [[ ! -d $path_dir ]]
then 
   echo "Print the list"
   exit 1
fi

if [[ ! -d $path_dir/archive ]]
then
   echo "All Good"
   exit 1
fi

for i in ( find $path_dir -maxdepth 1 -type d --size 10M )
do 
   if [[ 0 -qe 0 ]]
then 
   zip $i || exit 1
 fi
done 
   
